-- ====================================================================
-- PrepLab - Supabase PostgreSQL Schema & Security Policies
-- ====================================================================
-- Run this script in your Supabase Project SQL Editor to configure:
-- 1. Table structure (supports both fresh setups and existing tables)
-- 2. Row-Level Security (RLS) policies for single-user anonymous access
-- 3. Initial seed row for Fast Addition & Subtraction
-- ====================================================================

-- 1. Create Tables (if they do not already exist)
CREATE TABLE IF NOT EXISTS topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS test_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES topics(id) ON DELETE SET NULL,
    question_count INTEGER NOT NULL CHECK (question_count > 0),
    correct_count INTEGER NOT NULL CHECK (correct_count >= 0),
    accuracy NUMERIC(5, 2) NOT NULL CHECK (accuracy >= 0 AND accuracy <= 100),
    total_time_ms BIGINT NOT NULL CHECK (total_time_ms >= 0),
    average_time_ms BIGINT NOT NULL CHECK (average_time_ms >= 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS question_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL REFERENCES test_attempts(id) ON DELETE CASCADE,
    question_number INTEGER NOT NULL CHECK (question_number > 0),
    operation TEXT NOT NULL,
    question TEXT NOT NULL,
    correct_answer INTEGER NOT NULL,
    user_answer INTEGER,
    is_correct BOOLEAN NOT NULL,
    time_taken_ms BIGINT NOT NULL CHECK (time_taken_ms >= 0),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Indexes for High-Performance Queries
CREATE INDEX IF NOT EXISTS idx_test_attempts_topic_id ON test_attempts(topic_id);
CREATE INDEX IF NOT EXISTS idx_test_attempts_created_at ON test_attempts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_question_attempts_test_id ON question_attempts(test_id);

-- 3. Enable Row-Level Security (RLS)
ALTER TABLE topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_attempts ENABLE ROW LEVEL SECURITY;

-- 4. Clean up any prior policies
DROP POLICY IF EXISTS "Allow public read topics" ON topics;
DROP POLICY IF EXISTS "Allow public insert topics" ON topics;
DROP POLICY IF EXISTS "Allow anon read topics" ON topics;
DROP POLICY IF EXISTS "Allow anon insert topics" ON topics;

DROP POLICY IF EXISTS "Allow public read test_attempts" ON test_attempts;
DROP POLICY IF EXISTS "Allow public insert test_attempts" ON test_attempts;
DROP POLICY IF EXISTS "Allow anon read test_attempts" ON test_attempts;
DROP POLICY IF EXISTS "Allow anon insert test_attempts" ON test_attempts;

DROP POLICY IF EXISTS "Allow public read question_attempts" ON question_attempts;
DROP POLICY IF EXISTS "Allow public insert question_attempts" ON question_attempts;
DROP POLICY IF EXISTS "Allow anon read question_attempts" ON question_attempts;
DROP POLICY IF EXISTS "Allow anon insert question_attempts" ON question_attempts;

-- 5. Create Permissive Policies for Single-User Anonymous Frontend Access
-- Topics: SELECT and INSERT
CREATE POLICY "Allow anon read topics" ON topics
    FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow anon insert topics" ON topics
    FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Test Attempts: SELECT and INSERT
CREATE POLICY "Allow anon read test_attempts" ON test_attempts
    FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow anon insert test_attempts" ON test_attempts
    FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Question Attempts: SELECT and INSERT
CREATE POLICY "Allow anon read question_attempts" ON question_attempts
    FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow anon insert question_attempts" ON question_attempts
    FOR INSERT TO anon, authenticated WITH CHECK (true);

-- 6. Seed Fast Addition & Subtraction (Adaptive to id column type)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'topics' AND column_name = 'id' 
        AND data_type IN ('bigint', 'integer', 'smallint')
    ) THEN
        INSERT INTO topics (name, category)
        SELECT 'Fast Addition & Subtraction', 'Speed Math'
        WHERE NOT EXISTS (SELECT 1 FROM topics WHERE name = 'Fast Addition & Subtraction');
    ELSE
        INSERT INTO topics (id, name, category)
        VALUES ('fast-addition-subtraction', 'Fast Addition & Subtraction', 'Speed Math')
        ON CONFLICT DO NOTHING;
    END IF;
END $$;
